- environment:
    OS_AUTH_URL: "{{ osp_auth_url }}"
    OS_USERNAME: "{{ osp_auth_username }}"
    OS_PASSWORD: "{{ osp_auth_password }}"
    OS_PROJECT_NAME: "{{ osp_project_creation.project.name }}"
    OS_PROJECT_DOMAIN_ID: "{{ osp_auth_project_domain }}"
    OS_USER_DOMAIN_NAME: "{{ osp_auth_user_domain }}"

  block:
    - name: Create Heat stack from generated template
      command: >-
        openstack stack show -f json {{ guid }}-base-stack
      register: r_show
      failed_when: false
      changed_when: false
      tags: heat

    - when: r_show.rc == 0
      name: Update Heat stack from generated template
      command: >-
        openstack stack update --wait -t {{ heat_master_template }} {{ guid }}-base-stack
      register: r_hot_out

    - when: r_show.rc != 0
      name: Create Heat stack from generated template
      command: >-
        openstack stack create --wait -t {{ heat_master_template }} {{ guid }}-base-stack
      register: r_hot_out

    - set_fact:
        hot_output: "{{ r_hot_out }}"

    - debug:
        var: hot_output
